### ISSUE TITLE
更新一下 dnscrypt.info 上的信息？

### ISSUE THREAD

**Issue by imba-tjd** [xyzmos/GeekDNS#3]
https://github.com/DNSCrypt/dnscrypt-resolvers/issues/236

可能是因为你换了证书的关系，SimpleDNSCrypt全连不上了。

另外现在的stamps表示你的DNS是勾上了No Filter的，而我看你的论坛里很久以前的帖子说有过滤广告。不知道现在是哪样

**Comment by xyzmos** [comment]
很早就关闭了过滤规则，由于当前流量爆发增长，服务器抗不住，暂时开启白名单验证，或者走cdn通道。详情可以进交流群交流。
